// <auto-generated />
using System;
using CarStats.Data.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CarStats.Data.Migrations.CarDb
{
    [DbContext(typeof(CarDbContext))]
    [Migration("20250102114824_CardDbContextMigration")]
    partial class CardDbContextMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CarStats.Data.Models.Car", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("text");

                    b.Property<string>("car_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("created_time")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("player_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_time")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("id");

                    b.ToTable("cars");
                });

            modelBuilder.Entity("CarStats.Data.Models.CarExpenses", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("text");

                    b.Property<string>("car_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("date")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("price")
                        .HasColumnType("real");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("expenses");
                });
#pragma warning restore 612, 618
        }
    }
}
